POST http://localhost:3001/api/vocablogs
content-type: application/json

{
"spokenWords":[
    {
    "wordBank":"650d2691df78bbefe5a91340",
    "name":"banana",
    "peerComparisonScore":"2"
    }
],
"child":"65013686cdee43b25a88d802"
}

###

