POST http://localhost:3001/api/vocablogs
content-type: application/json

{
"spokenWords":[
    {
    "wordBank":"65098b15cf10e572d3b53eed",
    "name":"banana",
    "peerComparisonScore":"2"
    }
],
"child":"65013686cdee43b25a88d802"
}

###

